use super::Color;

pub struct ColorTrieNode {
    pub color: Option<u16>,
    pub children: (u16, u16),
}

pub static NODES: &[ColorTrieNode] = &[
    ColorTrieNode {
        color: None,
        children: (900, 20),
    },
    ColorTrieNode {
        color: None,
        children: (30, 4),
    },
    ColorTrieNode {
        color: None,
        children: (7, 1),
    },
    ColorTrieNode {
        color: None,
        children: (6, 1),
    },
    ColorTrieNode {
        color: None,
        children: (5, 1),
    },
    ColorTrieNode {
        color: None,
        children: (4, 1),
    },
    ColorTrieNode {
        color: None,
        children: (3, 1),
    },
    ColorTrieNode {
        color: None,
        children: (2, 1),
    },
    ColorTrieNode {
        color: None,
        children: (1, 1),
    },
    ColorTrieNode {
        color: None,
        children: (0, 1),
    },
    ColorTrieNode {
        color: Some(0),
        children: (0, 0),
    },
    ColorTrieNode {
        color: None,
        children: (18, 1),
    },
    ColorTrieNode {
        color: None,
        children: (17, 1),
    },
    ColorTrieNode {
        color: None,
        children: (16, 1),
    },
    ColorTrieNode {
        color: None,
        children: (15, 1),
    },
    ColorTrieNode {
        color: None,
        children: (14, 1),
    },
    ColorTrieNode {
        color: None,
        children: (13, 1),
    },
    ColorTrieNode {
        color: None,
        children: (12, 1),
    },
    ColorTrieNode {
        color: None,
        children: (11, 1),
    },
    ColorTrieNode {
        color: None,
        children: (10, 1),
    },
    ColorTrieNode {
        color: None,
        children: (9, 1),
    },
    ColorTrieNode {
        color: None,
        children: (8, 1),
    },
    ColorTrieNode {
        color: Some(1),
        children: (8, 0),
    },
    ColorTrieNode {
        color: None,
        children: (26, 1),
    },
    ColorTrieNode {
        color: None,
        children: (25, 1),
    },
    ColorTrieNode {
        color: Some(2),
        children: (24, 1),
    },
    ColorTrieNode {
        color: None,
        children: (23, 1),
    },
    ColorTrieNode {
        color: None,
        children: (22, 1),
    },
    ColorTrieNode {
        color: None,
        children: (21, 1),
    },
    ColorTrieNode {
        color: None,
        children: (20, 1),
    },
    ColorTrieNode {
        color: None,
        children: (19, 1),
    },
    ColorTrieNode {
        color: Some(3),
        children: (19, 0),
    },
    ColorTrieNode {
        color: None,
        children: (29, 1),
    },
    ColorTrieNode {
        color: None,
        children: (28, 1),
    },
    ColorTrieNode {
        color: None,
        children: (27, 1),
    },
    ColorTrieNode {
        color: Some(4),
        children: (27, 0),
    },
    ColorTrieNode {
        color: None,
        children: (76, 5),
    },
    ColorTrieNode {
        color: None,
        children: (36, 1),
    },
    ColorTrieNode {
        color: None,
        children: (35, 1),
    },
    ColorTrieNode {
        color: None,
        children: (34, 1),
    },
    ColorTrieNode {
        color: Some(5),
        children: (34, 0),
    },
    ColorTrieNode {
        color: None,
        children: (40, 1),
    },
    ColorTrieNode {
        color: None,
        children: (39, 1),
    },
    ColorTrieNode {
        color: None,
        children: (38, 1),
    },
    ColorTrieNode {
        color: None,
        children: (37, 1),
    },
    ColorTrieNode {
        color: Some(6),
        children: (37, 0),
    },
    ColorTrieNode {
        color: None,
        children: (63, 2),
    },
    ColorTrieNode {
        color: None,
        children: (53, 2),
    },
    ColorTrieNode {
        color: None,
        children: (41, 1),
    },
    ColorTrieNode {
        color: Some(7),
        children: (41, 0),
    },
    ColorTrieNode {
        color: None,
        children: (52, 1),
    },
    ColorTrieNode {
        color: None,
        children: (51, 1),
    },
    ColorTrieNode {
        color: None,
        children: (50, 1),
    },
    ColorTrieNode {
        color: None,
        children: (49, 1),
    },
    ColorTrieNode {
        color: None,
        children: (48, 1),
    },
    ColorTrieNode {
        color: None,
        children: (47, 1),
    },
    ColorTrieNode {
        color: None,
        children: (46, 1),
    },
    ColorTrieNode {
        color: None,
        children: (45, 1),
    },
    ColorTrieNode {
        color: None,
        children: (44, 1),
    },
    ColorTrieNode {
        color: None,
        children: (43, 1),
    },
    ColorTrieNode {
        color: None,
        children: (42, 1),
    },
    ColorTrieNode {
        color: Some(8),
        children: (42, 0),
    },
    ColorTrieNode {
        color: None,
        children: (62, 1),
    },
    ColorTrieNode {
        color: Some(9),
        children: (61, 1),
    },
    ColorTrieNode {
        color: None,
        children: (60, 1),
    },
    ColorTrieNode {
        color: None,
        children: (59, 1),
    },
    ColorTrieNode {
        color: None,
        children: (58, 1),
    },
    ColorTrieNode {
        color: None,
        children: (57, 1),
    },
    ColorTrieNode {
        color: None,
        children: (56, 1),
    },
    ColorTrieNode {
        color: None,
        children: (55, 1),
    },
    ColorTrieNode {
        color: Some(10),
        children: (55, 0),
    },
    ColorTrieNode {
        color: None,
        children: (67, 1),
    },
    ColorTrieNode {
        color: None,
        children: (66, 1),
    },
    ColorTrieNode {
        color: None,
        children: (65, 1),
    },
    ColorTrieNode {
        color: Some(11),
        children: (65, 0),
    },
    ColorTrieNode {
        color: None,
        children: (75, 1),
    },
    ColorTrieNode {
        color: None,
        children: (74, 1),
    },
    ColorTrieNode {
        color: None,
        children: (73, 1),
    },
    ColorTrieNode {
        color: None,
        children: (72, 1),
    },
    ColorTrieNode {
        color: None,
        children: (71, 1),
    },
    ColorTrieNode {
        color: None,
        children: (70, 1),
    },
    ColorTrieNode {
        color: None,
        children: (69, 1),
    },
    ColorTrieNode {
        color: None,
        children: (68, 1),
    },
    ColorTrieNode {
        color: Some(12),
        children: (68, 0),
    },
    ColorTrieNode {
        color: None,
        children: (130, 5),
    },
    ColorTrieNode {
        color: None,
        children: (88, 1),
    },
    ColorTrieNode {
        color: None,
        children: (87, 1),
    },
    ColorTrieNode {
        color: None,
        children: (86, 1),
    },
    ColorTrieNode {
        color: None,
        children: (85, 1),
    },
    ColorTrieNode {
        color: None,
        children: (84, 1),
    },
    ColorTrieNode {
        color: None,
        children: (83, 1),
    },
    ColorTrieNode {
        color: None,
        children: (82, 1),
    },
    ColorTrieNode {
        color: None,
        children: (81, 1),
    },
    ColorTrieNode {
        color: Some(13),
        children: (81, 0),
    },
    ColorTrieNode {
        color: None,
        children: (102, 2),
    },
    ColorTrieNode {
        color: None,
        children: (95, 1),
    },
    ColorTrieNode {
        color: None,
        children: (94, 1),
    },
    ColorTrieNode {
        color: None,
        children: (93, 1),
    },
    ColorTrieNode {
        color: None,
        children: (92, 1),
    },
    ColorTrieNode {
        color: None,
        children: (91, 1),
    },
    ColorTrieNode {
        color: None,
        children: (90, 1),
    },
    ColorTrieNode {
        color: None,
        children: (89, 1),
    },
    ColorTrieNode {
        color: Some(14),
        children: (89, 0),
    },
    ColorTrieNode {
        color: None,
        children: (101, 1),
    },
    ColorTrieNode {
        color: None,
        children: (100, 1),
    },
    ColorTrieNode {
        color: None,
        children: (99, 1),
    },
    ColorTrieNode {
        color: None,
        children: (98, 1),
    },
    ColorTrieNode {
        color: None,
        children: (97, 1),
    },
    ColorTrieNode {
        color: None,
        children: (96, 1),
    },
    ColorTrieNode {
        color: Some(15),
        children: (96, 0),
    },
    ColorTrieNode {
        color: None,
        children: (122, 1),
    },
    ColorTrieNode {
        color: None,
        children: (120, 2),
    },
    ColorTrieNode {
        color: None,
        children: (104, 1),
    },
    ColorTrieNode {
        color: Some(16),
        children: (104, 0),
    },
    ColorTrieNode {
        color: None,
        children: (118, 2),
    },
    ColorTrieNode {
        color: None,
        children: (114, 1),
    },
    ColorTrieNode {
        color: None,
        children: (113, 1),
    },
    ColorTrieNode {
        color: None,
        children: (112, 1),
    },
    ColorTrieNode {
        color: None,
        children: (111, 1),
    },
    ColorTrieNode {
        color: None,
        children: (110, 1),
    },
    ColorTrieNode {
        color: None,
        children: (109, 1),
    },
    ColorTrieNode {
        color: None,
        children: (108, 1),
    },
    ColorTrieNode {
        color: None,
        children: (107, 1),
    },
    ColorTrieNode {
        color: None,
        children: (106, 1),
    },
    ColorTrieNode {
        color: None,
        children: (105, 1),
    },
    ColorTrieNode {
        color: Some(17),
        children: (105, 0),
    },
    ColorTrieNode {
        color: None,
        children: (117, 1),
    },
    ColorTrieNode {
        color: None,
        children: (116, 1),
    },
    ColorTrieNode {
        color: None,
        children: (115, 1),
    },
    ColorTrieNode {
        color: Some(18),
        children: (115, 0),
    },
    ColorTrieNode {
        color: None,
        children: (127, 1),
    },
    ColorTrieNode {
        color: None,
        children: (126, 1),
    },
    ColorTrieNode {
        color: None,
        children: (125, 1),
    },
    ColorTrieNode {
        color: None,
        children: (124, 1),
    },
    ColorTrieNode {
        color: None,
        children: (123, 1),
    },
    ColorTrieNode {
        color: Some(19),
        children: (123, 0),
    },
    ColorTrieNode {
        color: None,
        children: (129, 1),
    },
    ColorTrieNode {
        color: None,
        children: (128, 1),
    },
    ColorTrieNode {
        color: Some(20),
        children: (128, 0),
    },
    ColorTrieNode {
        color: None,
        children: (264, 4),
    },
    ColorTrieNode {
        color: None,
        children: (234, 1),
    },
    ColorTrieNode {
        color: None,
        children: (233, 1),
    },
    ColorTrieNode {
        color: None,
        children: (232, 1),
    },
    ColorTrieNode {
        color: None,
        children: (222, 10),
    },
    ColorTrieNode {
        color: None,
        children: (137, 1),
    },
    ColorTrieNode {
        color: None,
        children: (136, 1),
    },
    ColorTrieNode {
        color: None,
        children: (135, 1),
    },
    ColorTrieNode {
        color: Some(21),
        children: (135, 0),
    },
    ColorTrieNode {
        color: None,
        children: (140, 1),
    },
    ColorTrieNode {
        color: None,
        children: (139, 1),
    },
    ColorTrieNode {
        color: None,
        children: (138, 1),
    },
    ColorTrieNode {
        color: Some(22),
        children: (138, 0),
    },
    ColorTrieNode {
        color: None,
        children: (153, 2),
    },
    ColorTrieNode {
        color: None,
        children: (147, 1),
    },
    ColorTrieNode {
        color: None,
        children: (146, 1),
    },
    ColorTrieNode {
        color: None,
        children: (145, 1),
    },
    ColorTrieNode {
        color: None,
        children: (144, 1),
    },
    ColorTrieNode {
        color: None,
        children: (143, 1),
    },
    ColorTrieNode {
        color: None,
        children: (142, 1),
    },
    ColorTrieNode {
        color: None,
        children: (141, 1),
    },
    ColorTrieNode {
        color: Some(23),
        children: (141, 0),
    },
    ColorTrieNode {
        color: None,
        children: (151, 2),
    },
    ColorTrieNode {
        color: None,
        children: (148, 1),
    },
    ColorTrieNode {
        color: Some(24),
        children: (148, 0),
    },
    ColorTrieNode {
        color: None,
        children: (150, 1),
    },
    ColorTrieNode {
        color: None,
        children: (149, 1),
    },
    ColorTrieNode {
        color: Some(25),
        children: (149, 0),
    },
    ColorTrieNode {
        color: None,
        children: (158, 1),
    },
    ColorTrieNode {
        color: None,
        children: (157, 1),
    },
    ColorTrieNode {
        color: None,
        children: (156, 1),
    },
    ColorTrieNode {
        color: None,
        children: (155, 1),
    },
    ColorTrieNode {
        color: Some(26),
        children: (155, 0),
    },
    ColorTrieNode {
        color: None,
        children: (164, 1),
    },
    ColorTrieNode {
        color: None,
        children: (163, 1),
    },
    ColorTrieNode {
        color: None,
        children: (162, 1),
    },
    ColorTrieNode {
        color: None,
        children: (161, 1),
    },
    ColorTrieNode {
        color: None,
        children: (160, 1),
    },
    ColorTrieNode {
        color: None,
        children: (159, 1),
    },
    ColorTrieNode {
        color: Some(27),
        children: (159, 0),
    },
    ColorTrieNode {
        color: None,
        children: (181, 2),
    },
    ColorTrieNode {
        color: None,
        children: (172, 1),
    },
    ColorTrieNode {
        color: None,
        children: (171, 1),
    },
    ColorTrieNode {
        color: None,
        children: (170, 1),
    },
    ColorTrieNode {
        color: None,
        children: (169, 1),
    },
    ColorTrieNode {
        color: None,
        children: (168, 1),
    },
    ColorTrieNode {
        color: None,
        children: (167, 1),
    },
    ColorTrieNode {
        color: None,
        children: (166, 1),
    },
    ColorTrieNode {
        color: None,
        children: (165, 1),
    },
    ColorTrieNode {
        color: Some(28),
        children: (165, 0),
    },
    ColorTrieNode {
        color: None,
        children: (179, 2),
    },
    ColorTrieNode {
        color: None,
        children: (175, 1),
    },
    ColorTrieNode {
        color: None,
        children: (174, 1),
    },
    ColorTrieNode {
        color: None,
        children: (173, 1),
    },
    ColorTrieNode {
        color: Some(29),
        children: (173, 0),
    },
    ColorTrieNode {
        color: None,
        children: (178, 1),
    },
    ColorTrieNode {
        color: None,
        children: (177, 1),
    },
    ColorTrieNode {
        color: None,
        children: (176, 1),
    },
    ColorTrieNode {
        color: Some(30),
        children: (176, 0),
    },
    ColorTrieNode {
        color: None,
        children: (184, 1),
    },
    ColorTrieNode {
        color: None,
        children: (183, 1),
    },
    ColorTrieNode {
        color: Some(31),
        children: (183, 0),
    },
    ColorTrieNode {
        color: None,
        children: (206, 3),
    },
    ColorTrieNode {
        color: None,
        children: (188, 1),
    },
    ColorTrieNode {
        color: None,
        children: (187, 1),
    },
    ColorTrieNode {
        color: None,
        children: (186, 1),
    },
    ColorTrieNode {
        color: None,
        children: (185, 1),
    },
    ColorTrieNode {
        color: Some(32),
        children: (185, 0),
    },
    ColorTrieNode {
        color: None,
        children: (194, 1),
    },
    ColorTrieNode {
        color: None,
        children: (193, 1),
    },
    ColorTrieNode {
        color: None,
        children: (192, 1),
    },
    ColorTrieNode {
        color: None,
        children: (191, 1),
    },
    ColorTrieNode {
        color: None,
        children: (190, 1),
    },
    ColorTrieNode {
        color: None,
        children: (189, 1),
    },
    ColorTrieNode {
        color: Some(33),
        children: (189, 0),
    },
    ColorTrieNode {
        color: None,
        children: (205, 1),
    },
    ColorTrieNode {
        color: None,
        children: (204, 1),
    },
    ColorTrieNode {
        color: None,
        children: (203, 1),
    },
    ColorTrieNode {
        color: None,
        children: (201, 2),
    },
    ColorTrieNode {
        color: None,
        children: (197, 1),
    },
    ColorTrieNode {
        color: None,
        children: (196, 1),
    },
    ColorTrieNode {
        color: None,
        children: (195, 1),
    },
    ColorTrieNode {
        color: Some(34),
        children: (195, 0),
    },
    ColorTrieNode {
        color: None,
        children: (200, 1),
    },
    ColorTrieNode {
        color: None,
        children: (199, 1),
    },
    ColorTrieNode {
        color: None,
        children: (198, 1),
    },
    ColorTrieNode {
        color: Some(35),
        children: (198, 0),
    },
    ColorTrieNode {
        color: None,
        children: (216, 1),
    },
    ColorTrieNode {
        color: None,
        children: (215, 1),
    },
    ColorTrieNode {
        color: None,
        children: (214, 1),
    },
    ColorTrieNode {
        color: None,
        children: (213, 1),
    },
    ColorTrieNode {
        color: None,
        children: (212, 1),
    },
    ColorTrieNode {
        color: None,
        children: (211, 1),
    },
    ColorTrieNode {
        color: None,
        children: (210, 1),
    },
    ColorTrieNode {
        color: None,
        children: (209, 1),
    },
    ColorTrieNode {
        color: Some(36),
        children: (209, 0),
    },
    ColorTrieNode {
        color: None,
        children: (221, 1),
    },
    ColorTrieNode {
        color: None,
        children: (220, 1),
    },
    ColorTrieNode {
        color: None,
        children: (219, 1),
    },
    ColorTrieNode {
        color: None,
        children: (218, 1),
    },
    ColorTrieNode {
        color: None,
        children: (217, 1),
    },
    ColorTrieNode {
        color: Some(37),
        children: (217, 0),
    },
    ColorTrieNode {
        color: None,
        children: (248, 1),
    },
    ColorTrieNode {
        color: None,
        children: (247, 1),
    },
    ColorTrieNode {
        color: None,
        children: (246, 1),
    },
    ColorTrieNode {
        color: None,
        children: (244, 2),
    },
    ColorTrieNode {
        color: None,
        children: (237, 1),
    },
    ColorTrieNode {
        color: None,
        children: (236, 1),
    },
    ColorTrieNode {
        color: None,
        children: (235, 1),
    },
    ColorTrieNode {
        color: Some(38),
        children: (235, 0),
    },
    ColorTrieNode {
        color: None,
        children: (243, 1),
    },
    ColorTrieNode {
        color: None,
        children: (242, 1),
    },
    ColorTrieNode {
        color: None,
        children: (241, 1),
    },
    ColorTrieNode {
        color: None,
        children: (240, 1),
    },
    ColorTrieNode {
        color: None,
        children: (239, 1),
    },
    ColorTrieNode {
        color: None,
        children: (238, 1),
    },
    ColorTrieNode {
        color: Some(39),
        children: (238, 0),
    },
    ColorTrieNode {
        color: None,
        children: (254, 1),
    },
    ColorTrieNode {
        color: None,
        children: (253, 1),
    },
    ColorTrieNode {
        color: None,
        children: (252, 1),
    },
    ColorTrieNode {
        color: None,
        children: (251, 1),
    },
    ColorTrieNode {
        color: None,
        children: (250, 1),
    },
    ColorTrieNode {
        color: None,
        children: (249, 1),
    },
    ColorTrieNode {
        color: Some(40),
        children: (249, 0),
    },
    ColorTrieNode {
        color: None,
        children: (263, 1),
    },
    ColorTrieNode {
        color: None,
        children: (262, 1),
    },
    ColorTrieNode {
        color: None,
        children: (261, 1),
    },
    ColorTrieNode {
        color: None,
        children: (260, 1),
    },
    ColorTrieNode {
        color: None,
        children: (259, 1),
    },
    ColorTrieNode {
        color: None,
        children: (258, 1),
    },
    ColorTrieNode {
        color: None,
        children: (257, 1),
    },
    ColorTrieNode {
        color: None,
        children: (256, 1),
    },
    ColorTrieNode {
        color: None,
        children: (255, 1),
    },
    ColorTrieNode {
        color: Some(41),
        children: (255, 0),
    },
    ColorTrieNode {
        color: None,
        children: (300, 4),
    },
    ColorTrieNode {
        color: None,
        children: (274, 1),
    },
    ColorTrieNode {
        color: None,
        children: (273, 1),
    },
    ColorTrieNode {
        color: None,
        children: (272, 1),
    },
    ColorTrieNode {
        color: None,
        children: (271, 1),
    },
    ColorTrieNode {
        color: None,
        children: (270, 1),
    },
    ColorTrieNode {
        color: None,
        children: (269, 1),
    },
    ColorTrieNode {
        color: None,
        children: (268, 1),
    },
    ColorTrieNode {
        color: Some(42),
        children: (268, 0),
    },
    ColorTrieNode {
        color: None,
        children: (284, 1),
    },
    ColorTrieNode {
        color: None,
        children: (283, 1),
    },
    ColorTrieNode {
        color: None,
        children: (282, 1),
    },
    ColorTrieNode {
        color: None,
        children: (281, 1),
    },
    ColorTrieNode {
        color: None,
        children: (280, 1),
    },
    ColorTrieNode {
        color: None,
        children: (279, 1),
    },
    ColorTrieNode {
        color: None,
        children: (278, 1),
    },
    ColorTrieNode {
        color: None,
        children: (277, 1),
    },
    ColorTrieNode {
        color: None,
        children: (276, 1),
    },
    ColorTrieNode {
        color: None,
        children: (275, 1),
    },
    ColorTrieNode {
        color: Some(43),
        children: (275, 0),
    },
    ColorTrieNode {
        color: None,
        children: (294, 1),
    },
    ColorTrieNode {
        color: None,
        children: (293, 1),
    },
    ColorTrieNode {
        color: None,
        children: (292, 1),
    },
    ColorTrieNode {
        color: None,
        children: (291, 1),
    },
    ColorTrieNode {
        color: None,
        children: (290, 1),
    },
    ColorTrieNode {
        color: None,
        children: (289, 1),
    },
    ColorTrieNode {
        color: None,
        children: (288, 1),
    },
    ColorTrieNode {
        color: None,
        children: (287, 1),
    },
    ColorTrieNode {
        color: None,
        children: (286, 1),
    },
    ColorTrieNode {
        color: None,
        children: (285, 1),
    },
    ColorTrieNode {
        color: Some(44),
        children: (285, 0),
    },
    ColorTrieNode {
        color: None,
        children: (299, 1),
    },
    ColorTrieNode {
        color: None,
        children: (298, 1),
    },
    ColorTrieNode {
        color: None,
        children: (297, 1),
    },
    ColorTrieNode {
        color: None,
        children: (296, 1),
    },
    ColorTrieNode {
        color: None,
        children: (295, 1),
    },
    ColorTrieNode {
        color: Some(45),
        children: (295, 0),
    },
    ColorTrieNode {
        color: None,
        children: (339, 4),
    },
    ColorTrieNode {
        color: None,
        children: (310, 1),
    },
    ColorTrieNode {
        color: None,
        children: (309, 1),
    },
    ColorTrieNode {
        color: None,
        children: (308, 1),
    },
    ColorTrieNode {
        color: None,
        children: (307, 1),
    },
    ColorTrieNode {
        color: None,
        children: (306, 1),
    },
    ColorTrieNode {
        color: None,
        children: (305, 1),
    },
    ColorTrieNode {
        color: None,
        children: (304, 1),
    },
    ColorTrieNode {
        color: Some(46),
        children: (304, 0),
    },
    ColorTrieNode {
        color: None,
        children: (319, 1),
    },
    ColorTrieNode {
        color: None,
        children: (318, 1),
    },
    ColorTrieNode {
        color: None,
        children: (317, 1),
    },
    ColorTrieNode {
        color: None,
        children: (316, 1),
    },
    ColorTrieNode {
        color: None,
        children: (315, 1),
    },
    ColorTrieNode {
        color: None,
        children: (314, 1),
    },
    ColorTrieNode {
        color: None,
        children: (313, 1),
    },
    ColorTrieNode {
        color: None,
        children: (312, 1),
    },
    ColorTrieNode {
        color: None,
        children: (311, 1),
    },
    ColorTrieNode {
        color: Some(47),
        children: (311, 0),
    },
    ColorTrieNode {
        color: None,
        children: (326, 1),
    },
    ColorTrieNode {
        color: None,
        children: (325, 1),
    },
    ColorTrieNode {
        color: Some(48),
        children: (324, 1),
    },
    ColorTrieNode {
        color: None,
        children: (323, 1),
    },
    ColorTrieNode {
        color: None,
        children: (322, 1),
    },
    ColorTrieNode {
        color: None,
        children: (321, 1),
    },
    ColorTrieNode {
        color: None,
        children: (320, 1),
    },
    ColorTrieNode {
        color: Some(49),
        children: (320, 0),
    },
    ColorTrieNode {
        color: None,
        children: (337, 2),
    },
    ColorTrieNode {
        color: None,
        children: (327, 1),
    },
    ColorTrieNode {
        color: Some(50),
        children: (327, 0),
    },
    ColorTrieNode {
        color: None,
        children: (336, 1),
    },
    ColorTrieNode {
        color: None,
        children: (335, 1),
    },
    ColorTrieNode {
        color: Some(51),
        children: (334, 1),
    },
    ColorTrieNode {
        color: None,
        children: (333, 1),
    },
    ColorTrieNode {
        color: None,
        children: (332, 1),
    },
    ColorTrieNode {
        color: None,
        children: (331, 1),
    },
    ColorTrieNode {
        color: None,
        children: (330, 1),
    },
    ColorTrieNode {
        color: None,
        children: (329, 1),
    },
    ColorTrieNode {
        color: None,
        children: (328, 1),
    },
    ColorTrieNode {
        color: Some(52),
        children: (328, 0),
    },
    ColorTrieNode {
        color: None,
        children: (355, 1),
    },
    ColorTrieNode {
        color: None,
        children: (353, 2),
    },
    ColorTrieNode {
        color: None,
        children: (347, 1),
    },
    ColorTrieNode {
        color: None,
        children: (346, 1),
    },
    ColorTrieNode {
        color: None,
        children: (345, 1),
    },
    ColorTrieNode {
        color: None,
        children: (344, 1),
    },
    ColorTrieNode {
        color: None,
        children: (343, 1),
    },
    ColorTrieNode {
        color: Some(53),
        children: (343, 0),
    },
    ColorTrieNode {
        color: None,
        children: (352, 1),
    },
    ColorTrieNode {
        color: None,
        children: (351, 1),
    },
    ColorTrieNode {
        color: None,
        children: (350, 1),
    },
    ColorTrieNode {
        color: None,
        children: (349, 1),
    },
    ColorTrieNode {
        color: None,
        children: (348, 1),
    },
    ColorTrieNode {
        color: Some(54),
        children: (348, 0),
    },
    ColorTrieNode {
        color: None,
        children: (369, 2),
    },
    ColorTrieNode {
        color: None,
        children: (365, 1),
    },
    ColorTrieNode {
        color: None,
        children: (364, 1),
    },
    ColorTrieNode {
        color: None,
        children: (362, 2),
    },
    ColorTrieNode {
        color: None,
        children: (360, 1),
    },
    ColorTrieNode {
        color: None,
        children: (359, 1),
    },
    ColorTrieNode {
        color: None,
        children: (358, 1),
    },
    ColorTrieNode {
        color: None,
        children: (357, 1),
    },
    ColorTrieNode {
        color: None,
        children: (356, 1),
    },
    ColorTrieNode {
        color: Some(55),
        children: (356, 0),
    },
    ColorTrieNode {
        color: None,
        children: (361, 1),
    },
    ColorTrieNode {
        color: Some(56),
        children: (361, 0),
    },
    ColorTrieNode {
        color: None,
        children: (368, 1),
    },
    ColorTrieNode {
        color: None,
        children: (367, 1),
    },
    ColorTrieNode {
        color: None,
        children: (366, 1),
    },
    ColorTrieNode {
        color: Some(57),
        children: (366, 0),
    },
    ColorTrieNode {
        color: None,
        children: (374, 1),
    },
    ColorTrieNode {
        color: None,
        children: (373, 1),
    },
    ColorTrieNode {
        color: None,
        children: (372, 1),
    },
    ColorTrieNode {
        color: None,
        children: (371, 1),
    },
    ColorTrieNode {
        color: Some(58),
        children: (371, 0),
    },
    ColorTrieNode {
        color: None,
        children: (499, 3),
    },
    ColorTrieNode {
        color: None,
        children: (393, 2),
    },
    ColorTrieNode {
        color: None,
        children: (385, 1),
    },
    ColorTrieNode {
        color: None,
        children: (384, 1),
    },
    ColorTrieNode {
        color: None,
        children: (383, 1),
    },
    ColorTrieNode {
        color: None,
        children: (382, 1),
    },
    ColorTrieNode {
        color: None,
        children: (381, 1),
    },
    ColorTrieNode {
        color: Some(59),
        children: (380, 1),
    },
    ColorTrieNode {
        color: None,
        children: (379, 1),
    },
    ColorTrieNode {
        color: None,
        children: (378, 1),
    },
    ColorTrieNode {
        color: None,
        children: (377, 1),
    },
    ColorTrieNode {
        color: None,
        children: (376, 1),
    },
    ColorTrieNode {
        color: None,
        children: (375, 1),
    },
    ColorTrieNode {
        color: Some(60),
        children: (375, 0),
    },
    ColorTrieNode {
        color: None,
        children: (392, 1),
    },
    ColorTrieNode {
        color: None,
        children: (391, 1),
    },
    ColorTrieNode {
        color: None,
        children: (390, 1),
    },
    ColorTrieNode {
        color: None,
        children: (389, 1),
    },
    ColorTrieNode {
        color: None,
        children: (388, 1),
    },
    ColorTrieNode {
        color: None,
        children: (387, 1),
    },
    ColorTrieNode {
        color: None,
        children: (386, 1),
    },
    ColorTrieNode {
        color: Some(61),
        children: (386, 0),
    },
    ColorTrieNode {
        color: None,
        children: (405, 1),
    },
    ColorTrieNode {
        color: None,
        children: (404, 1),
    },
    ColorTrieNode {
        color: None,
        children: (403, 1),
    },
    ColorTrieNode {
        color: None,
        children: (402, 1),
    },
    ColorTrieNode {
        color: None,
        children: (401, 1),
    },
    ColorTrieNode {
        color: None,
        children: (400, 1),
    },
    ColorTrieNode {
        color: None,
        children: (399, 1),
    },
    ColorTrieNode {
        color: None,
        children: (398, 1),
    },
    ColorTrieNode {
        color: None,
        children: (397, 1),
    },
    ColorTrieNode {
        color: None,
        children: (396, 1),
    },
    ColorTrieNode {
        color: None,
        children: (395, 1),
    },
    ColorTrieNode {
        color: Some(62),
        children: (395, 0),
    },
    ColorTrieNode {
        color: None,
        children: (496, 3),
    },
    ColorTrieNode {
        color: None,
        children: (486, 1),
    },
    ColorTrieNode {
        color: None,
        children: (485, 1),
    },
    ColorTrieNode {
        color: None,
        children: (484, 1),
    },
    ColorTrieNode {
        color: None,
        children: (478, 6),
    },
    ColorTrieNode {
        color: None,
        children: (408, 1),
    },
    ColorTrieNode {
        color: None,
        children: (407, 1),
    },
    ColorTrieNode {
        color: None,
        children: (406, 1),
    },
    ColorTrieNode {
        color: Some(63),
        children: (406, 0),
    },
    ColorTrieNode {
        color: None,
        children: (414, 2),
    },
    ColorTrieNode {
        color: None,
        children: (411, 1),
    },
    ColorTrieNode {
        color: None,
        children: (410, 1),
    },
    ColorTrieNode {
        color: None,
        children: (409, 1),
    },
    ColorTrieNode {
        color: Some(64),
        children: (409, 0),
    },
    ColorTrieNode {
        color: None,
        children: (413, 1),
    },
    ColorTrieNode {
        color: None,
        children: (412, 1),
    },
    ColorTrieNode {
        color: Some(65),
        children: (412, 0),
    },
    ColorTrieNode {
        color: None,
        children: (434, 2),
    },
    ColorTrieNode {
        color: None,
        children: (428, 1),
    },
    ColorTrieNode {
        color: None,
        children: (427, 1),
    },
    ColorTrieNode {
        color: None,
        children: (426, 1),
    },
    ColorTrieNode {
        color: None,
        children: (425, 1),
    },
    ColorTrieNode {
        color: None,
        children: (424, 1),
    },
    ColorTrieNode {
        color: None,
        children: (423, 1),
    },
    ColorTrieNode {
        color: None,
        children: (422, 1),
    },
    ColorTrieNode {
        color: None,
        children: (421, 1),
    },
    ColorTrieNode {
        color: None,
        children: (420, 1),
    },
    ColorTrieNode {
        color: None,
        children: (419, 1),
    },
    ColorTrieNode {
        color: None,
        children: (418, 1),
    },
    ColorTrieNode {
        color: None,
        children: (417, 1),
    },
    ColorTrieNode {
        color: None,
        children: (416, 1),
    },
    ColorTrieNode {
        color: Some(66),
        children: (416, 0),
    },
    ColorTrieNode {
        color: None,
        children: (432, 2),
    },
    ColorTrieNode {
        color: None,
        children: (429, 1),
    },
    ColorTrieNode {
        color: Some(68),
        children: (429, 0),
    },
    ColorTrieNode {
        color: None,
        children: (431, 1),
    },
    ColorTrieNode {
        color: None,
        children: (430, 1),
    },
    ColorTrieNode {
        color: Some(67),
        children: (430, 0),
    },
    ColorTrieNode {
        color: None,
        children: (438, 1),
    },
    ColorTrieNode {
        color: None,
        children: (437, 1),
    },
    ColorTrieNode {
        color: None,
        children: (436, 1),
    },
    ColorTrieNode {
        color: Some(69),
        children: (436, 0),
    },
    ColorTrieNode {
        color: None,
        children: (468, 5),
    },
    ColorTrieNode {
        color: None,
        children: (442, 1),
    },
    ColorTrieNode {
        color: None,
        children: (441, 1),
    },
    ColorTrieNode {
        color: None,
        children: (440, 1),
    },
    ColorTrieNode {
        color: None,
        children: (439, 1),
    },
    ColorTrieNode {
        color: Some(70),
        children: (439, 0),
    },
    ColorTrieNode {
        color: None,
        children: (448, 1),
    },
    ColorTrieNode {
        color: None,
        children: (447, 1),
    },
    ColorTrieNode {
        color: None,
        children: (446, 1),
    },
    ColorTrieNode {
        color: None,
        children: (445, 1),
    },
    ColorTrieNode {
        color: None,
        children: (444, 1),
    },
    ColorTrieNode {
        color: None,
        children: (443, 1),
    },
    ColorTrieNode {
        color: Some(71),
        children: (443, 0),
    },
    ColorTrieNode {
        color: None,
        children: (453, 1),
    },
    ColorTrieNode {
        color: None,
        children: (452, 1),
    },
    ColorTrieNode {
        color: None,
        children: (451, 1),
    },
    ColorTrieNode {
        color: None,
        children: (450, 1),
    },
    ColorTrieNode {
        color: None,
        children: (449, 1),
    },
    ColorTrieNode {
        color: Some(72),
        children: (449, 0),
    },
    ColorTrieNode {
        color: None,
        children: (460, 1),
    },
    ColorTrieNode {
        color: None,
        children: (459, 1),
    },
    ColorTrieNode {
        color: None,
        children: (458, 1),
    },
    ColorTrieNode {
        color: None,
        children: (457, 1),
    },
    ColorTrieNode {
        color: None,
        children: (456, 1),
    },
    ColorTrieNode {
        color: None,
        children: (455, 1),
    },
    ColorTrieNode {
        color: None,
        children: (454, 1),
    },
    ColorTrieNode {
        color: Some(73),
        children: (454, 0),
    },
    ColorTrieNode {
        color: None,
        children: (467, 1),
    },
    ColorTrieNode {
        color: None,
        children: (466, 1),
    },
    ColorTrieNode {
        color: None,
        children: (465, 1),
    },
    ColorTrieNode {
        color: None,
        children: (464, 1),
    },
    ColorTrieNode {
        color: None,
        children: (463, 1),
    },
    ColorTrieNode {
        color: None,
        children: (462, 1),
    },
    ColorTrieNode {
        color: None,
        children: (461, 1),
    },
    ColorTrieNode {
        color: Some(74),
        children: (461, 0),
    },
    ColorTrieNode {
        color: None,
        children: (477, 1),
    },
    ColorTrieNode {
        color: None,
        children: (476, 1),
    },
    ColorTrieNode {
        color: None,
        children: (475, 1),
    },
    ColorTrieNode {
        color: None,
        children: (474, 1),
    },
    ColorTrieNode {
        color: None,
        children: (473, 1),
    },
    ColorTrieNode {
        color: Some(75),
        children: (473, 0),
    },
    ColorTrieNode {
        color: None,
        children: (493, 1),
    },
    ColorTrieNode {
        color: Some(76),
        children: (492, 1),
    },
    ColorTrieNode {
        color: None,
        children: (491, 1),
    },
    ColorTrieNode {
        color: None,
        children: (490, 1),
    },
    ColorTrieNode {
        color: None,
        children: (489, 1),
    },
    ColorTrieNode {
        color: None,
        children: (488, 1),
    },
    ColorTrieNode {
        color: None,
        children: (487, 1),
    },
    ColorTrieNode {
        color: Some(77),
        children: (487, 0),
    },
    ColorTrieNode {
        color: None,
        children: (495, 1),
    },
    ColorTrieNode {
        color: None,
        children: (494, 1),
    },
    ColorTrieNode {
        color: Some(78),
        children: (494, 0),
    },
    ColorTrieNode {
        color: None,
        children: (619, 4),
    },
    ColorTrieNode {
        color: None,
        children: (509, 2),
    },
    ColorTrieNode {
        color: None,
        children: (505, 1),
    },
    ColorTrieNode {
        color: None,
        children: (504, 1),
    },
    ColorTrieNode {
        color: None,
        children: (503, 1),
    },
    ColorTrieNode {
        color: None,
        children: (502, 1),
    },
    ColorTrieNode {
        color: Some(79),
        children: (502, 0),
    },
    ColorTrieNode {
        color: None,
        children: (508, 1),
    },
    ColorTrieNode {
        color: None,
        children: (507, 1),
    },
    ColorTrieNode {
        color: None,
        children: (506, 1),
    },
    ColorTrieNode {
        color: Some(80),
        children: (506, 0),
    },
    ColorTrieNode {
        color: None,
        children: (585, 1),
    },
    ColorTrieNode {
        color: None,
        children: (584, 1),
    },
    ColorTrieNode {
        color: None,
        children: (583, 1),
    },
    ColorTrieNode {
        color: None,
        children: (582, 1),
    },
    ColorTrieNode {
        color: None,
        children: (581, 1),
    },
    ColorTrieNode {
        color: None,
        children: (574, 7),
    },
    ColorTrieNode {
        color: None,
        children: (519, 1),
    },
    ColorTrieNode {
        color: None,
        children: (518, 1),
    },
    ColorTrieNode {
        color: None,
        children: (517, 1),
    },
    ColorTrieNode {
        color: None,
        children: (516, 1),
    },
    ColorTrieNode {
        color: None,
        children: (515, 1),
    },
    ColorTrieNode {
        color: None,
        children: (514, 1),
    },
    ColorTrieNode {
        color: None,
        children: (513, 1),
    },
    ColorTrieNode {
        color: None,
        children: (512, 1),
    },
    ColorTrieNode {
        color: None,
        children: (511, 1),
    },
    ColorTrieNode {
        color: Some(81),
        children: (511, 0),
    },
    ColorTrieNode {
        color: None,
        children: (522, 1),
    },
    ColorTrieNode {
        color: None,
        children: (521, 1),
    },
    ColorTrieNode {
        color: None,
        children: (520, 1),
    },
    ColorTrieNode {
        color: Some(82),
        children: (520, 0),
    },
    ColorTrieNode {
        color: None,
        children: (527, 1),
    },
    ColorTrieNode {
        color: None,
        children: (526, 1),
    },
    ColorTrieNode {
        color: None,
        children: (525, 1),
    },
    ColorTrieNode {
        color: None,
        children: (524, 1),
    },
    ColorTrieNode {
        color: None,
        children: (523, 1),
    },
    ColorTrieNode {
        color: Some(83),
        children: (523, 0),
    },
    ColorTrieNode {
        color: None,
        children: (532, 1),
    },
    ColorTrieNode {
        color: None,
        children: (531, 1),
    },
    ColorTrieNode {
        color: None,
        children: (530, 1),
    },
    ColorTrieNode {
        color: None,
        children: (529, 1),
    },
    ColorTrieNode {
        color: None,
        children: (528, 1),
    },
    ColorTrieNode {
        color: Some(84),
        children: (528, 0),
    },
    ColorTrieNode {
        color: None,
        children: (555, 3),
    },
    ColorTrieNode {
        color: None,
        children: (538, 1),
    },
    ColorTrieNode {
        color: None,
        children: (537, 1),
    },
    ColorTrieNode {
        color: None,
        children: (536, 1),
    },
    ColorTrieNode {
        color: None,
        children: (535, 1),
    },
    ColorTrieNode {
        color: None,
        children: (534, 1),
    },
    ColorTrieNode {
        color: None,
        children: (533, 1),
    },
    ColorTrieNode {
        color: Some(85),
        children: (533, 0),
    },
    ColorTrieNode {
        color: None,
        children: (545, 1),
    },
    ColorTrieNode {
        color: None,
        children: (544, 1),
    },
    ColorTrieNode {
        color: None,
        children: (543, 1),
    },
    ColorTrieNode {
        color: None,
        children: (542, 1),
    },
    ColorTrieNode {
        color: None,
        children: (541, 1),
    },
    ColorTrieNode {
        color: None,
        children: (540, 1),
    },
    ColorTrieNode {
        color: None,
        children: (539, 1),
    },
    ColorTrieNode {
        color: Some(86),
        children: (539, 0),
    },
    ColorTrieNode {
        color: None,
        children: (554, 1),
    },
    ColorTrieNode {
        color: None,
        children: (553, 1),
    },
    ColorTrieNode {
        color: None,
        children: (552, 1),
    },
    ColorTrieNode {
        color: None,
        children: (551, 1),
    },
    ColorTrieNode {
        color: None,
        children: (550, 1),
    },
    ColorTrieNode {
        color: None,
        children: (549, 1),
    },
    ColorTrieNode {
        color: None,
        children: (548, 1),
    },
    ColorTrieNode {
        color: None,
        children: (547, 1),
    },
    ColorTrieNode {
        color: None,
        children: (546, 1),
    },
    ColorTrieNode {
        color: Some(87),
        children: (546, 0),
    },
    ColorTrieNode {
        color: None,
        children: (565, 1),
    },
    ColorTrieNode {
        color: None,
        children: (564, 1),
    },
    ColorTrieNode {
        color: None,
        children: (563, 1),
    },
    ColorTrieNode {
        color: None,
        children: (562, 1),
    },
    ColorTrieNode {
        color: None,
        children: (561, 1),
    },
    ColorTrieNode {
        color: None,
        children: (560, 1),
    },
    ColorTrieNode {
        color: None,
        children: (559, 1),
    },
    ColorTrieNode {
        color: None,
        children: (558, 1),
    },
    ColorTrieNode {
        color: Some(88),
        children: (558, 0),
    },
    ColorTrieNode {
        color: None,
        children: (573, 1),
    },
    ColorTrieNode {
        color: None,
        children: (572, 1),
    },
    ColorTrieNode {
        color: None,
        children: (571, 1),
    },
    ColorTrieNode {
        color: None,
        children: (570, 1),
    },
    ColorTrieNode {
        color: None,
        children: (569, 1),
    },
    ColorTrieNode {
        color: None,
        children: (568, 1),
    },
    ColorTrieNode {
        color: None,
        children: (567, 1),
    },
    ColorTrieNode {
        color: None,
        children: (566, 1),
    },
    ColorTrieNode {
        color: Some(89),
        children: (566, 0),
    },
    ColorTrieNode {
        color: None,
        children: (610, 3),
    },
    ColorTrieNode {
        color: None,
        children: (595, 1),
    },
    ColorTrieNode {
        color: None,
        children: (594, 1),
    },
    ColorTrieNode {
        color: None,
        children: (593, 1),
    },
    ColorTrieNode {
        color: None,
        children: (592, 1),
    },
    ColorTrieNode {
        color: None,
        children: (591, 1),
    },
    ColorTrieNode {
        color: None,
        children: (590, 1),
    },
    ColorTrieNode {
        color: None,
        children: (589, 1),
    },
    ColorTrieNode {
        color: None,
        children: (588, 1),
    },
    ColorTrieNode {
        color: None,
        children: (587, 1),
    },
    ColorTrieNode {
        color: None,
        children: (586, 1),
    },
    ColorTrieNode {
        color: Some(90),
        children: (586, 0),
    },
    ColorTrieNode {
        color: None,
        children: (602, 1),
    },
    ColorTrieNode {
        color: None,
        children: (601, 1),
    },
    ColorTrieNode {
        color: None,
        children: (600, 1),
    },
    ColorTrieNode {
        color: None,
        children: (599, 1),
    },
    ColorTrieNode {
        color: None,
        children: (598, 1),
    },
    ColorTrieNode {
        color: None,
        children: (597, 1),
    },
    ColorTrieNode {
        color: None,
        children: (596, 1),
    },
    ColorTrieNode {
        color: Some(91),
        children: (596, 0),
    },
    ColorTrieNode {
        color: None,
        children: (609, 1),
    },
    ColorTrieNode {
        color: None,
        children: (608, 1),
    },
    ColorTrieNode {
        color: None,
        children: (607, 1),
    },
    ColorTrieNode {
        color: None,
        children: (606, 1),
    },
    ColorTrieNode {
        color: None,
        children: (605, 1),
    },
    ColorTrieNode {
        color: None,
        children: (604, 1),
    },
    ColorTrieNode {
        color: None,
        children: (603, 1),
    },
    ColorTrieNode {
        color: Some(92),
        children: (603, 0),
    },
    ColorTrieNode {
        color: None,
        children: (618, 1),
    },
    ColorTrieNode {
        color: None,
        children: (617, 1),
    },
    ColorTrieNode {
        color: None,
        children: (616, 1),
    },
    ColorTrieNode {
        color: None,
        children: (615, 1),
    },
    ColorTrieNode {
        color: None,
        children: (614, 1),
    },
    ColorTrieNode {
        color: None,
        children: (613, 1),
    },
    ColorTrieNode {
        color: Some(93),
        children: (613, 0),
    },
    ColorTrieNode {
        color: None,
        children: (634, 1),
    },
    ColorTrieNode {
        color: None,
        children: (633, 1),
    },
    ColorTrieNode {
        color: None,
        children: (631, 2),
    },
    ColorTrieNode {
        color: None,
        children: (630, 1),
    },
    ColorTrieNode {
        color: None,
        children: (629, 1),
    },
    ColorTrieNode {
        color: None,
        children: (628, 1),
    },
    ColorTrieNode {
        color: None,
        children: (627, 1),
    },
    ColorTrieNode {
        color: None,
        children: (626, 1),
    },
    ColorTrieNode {
        color: None,
        children: (625, 1),
    },
    ColorTrieNode {
        color: None,
        children: (624, 1),
    },
    ColorTrieNode {
        color: None,
        children: (623, 1),
    },
    ColorTrieNode {
        color: Some(94),
        children: (623, 0),
    },
    ColorTrieNode {
        color: Some(95),
        children: (631, 0),
    },
    ColorTrieNode {
        color: None,
        children: (661, 2),
    },
    ColorTrieNode {
        color: None,
        children: (647, 2),
    },
    ColorTrieNode {
        color: None,
        children: (639, 1),
    },
    ColorTrieNode {
        color: None,
        children: (638, 1),
    },
    ColorTrieNode {
        color: None,
        children: (637, 1),
    },
    ColorTrieNode {
        color: None,
        children: (636, 1),
    },
    ColorTrieNode {
        color: None,
        children: (635, 1),
    },
    ColorTrieNode {
        color: Some(96),
        children: (635, 0),
    },
    ColorTrieNode {
        color: None,
        children: (646, 1),
    },
    ColorTrieNode {
        color: None,
        children: (645, 1),
    },
    ColorTrieNode {
        color: Some(97),
        children: (644, 1),
    },
    ColorTrieNode {
        color: None,
        children: (643, 1),
    },
    ColorTrieNode {
        color: None,
        children: (642, 1),
    },
    ColorTrieNode {
        color: None,
        children: (641, 1),
    },
    ColorTrieNode {
        color: None,
        children: (640, 1),
    },
    ColorTrieNode {
        color: Some(98),
        children: (640, 0),
    },
    ColorTrieNode {
        color: None,
        children: (659, 2),
    },
    ColorTrieNode {
        color: None,
        children: (655, 1),
    },
    ColorTrieNode {
        color: None,
        children: (654, 1),
    },
    ColorTrieNode {
        color: None,
        children: (653, 1),
    },
    ColorTrieNode {
        color: Some(99),
        children: (652, 1),
    },
    ColorTrieNode {
        color: None,
        children: (651, 1),
    },
    ColorTrieNode {
        color: None,
        children: (650, 1),
    },
    ColorTrieNode {
        color: None,
        children: (649, 1),
    },
    ColorTrieNode {
        color: Some(100),
        children: (649, 0),
    },
    ColorTrieNode {
        color: None,
        children: (658, 1),
    },
    ColorTrieNode {
        color: None,
        children: (657, 1),
    },
    ColorTrieNode {
        color: None,
        children: (656, 1),
    },
    ColorTrieNode {
        color: Some(101),
        children: (656, 0),
    },
    ColorTrieNode {
        color: None,
        children: (733, 6),
    },
    ColorTrieNode {
        color: None,
        children: (704, 2),
    },
    ColorTrieNode {
        color: None,
        children: (695, 1),
    },
    ColorTrieNode {
        color: None,
        children: (694, 1),
    },
    ColorTrieNode {
        color: None,
        children: (691, 3),
    },
    ColorTrieNode {
        color: None,
        children: (673, 2),
    },
    ColorTrieNode {
        color: None,
        children: (669, 1),
    },
    ColorTrieNode {
        color: None,
        children: (668, 1),
    },
    ColorTrieNode {
        color: None,
        children: (667, 1),
    },
    ColorTrieNode {
        color: None,
        children: (666, 1),
    },
    ColorTrieNode {
        color: None,
        children: (665, 1),
    },
    ColorTrieNode {
        color: None,
        children: (664, 1),
    },
    ColorTrieNode {
        color: None,
        children: (663, 1),
    },
    ColorTrieNode {
        color: Some(102),
        children: (663, 0),
    },
    ColorTrieNode {
        color: None,
        children: (672, 1),
    },
    ColorTrieNode {
        color: None,
        children: (671, 1),
    },
    ColorTrieNode {
        color: None,
        children: (670, 1),
    },
    ColorTrieNode {
        color: Some(103),
        children: (670, 0),
    },
    ColorTrieNode {
        color: None,
        children: (682, 1),
    },
    ColorTrieNode {
        color: None,
        children: (681, 1),
    },
    ColorTrieNode {
        color: None,
        children: (680, 1),
    },
    ColorTrieNode {
        color: None,
        children: (679, 1),
    },
    ColorTrieNode {
        color: None,
        children: (678, 1),
    },
    ColorTrieNode {
        color: None,
        children: (677, 1),
    },
    ColorTrieNode {
        color: None,
        children: (676, 1),
    },
    ColorTrieNode {
        color: None,
        children: (675, 1),
    },
    ColorTrieNode {
        color: Some(104),
        children: (675, 0),
    },
    ColorTrieNode {
        color: None,
        children: (690, 1),
    },
    ColorTrieNode {
        color: None,
        children: (689, 1),
    },
    ColorTrieNode {
        color: None,
        children: (688, 1),
    },
    ColorTrieNode {
        color: None,
        children: (687, 1),
    },
    ColorTrieNode {
        color: None,
        children: (686, 1),
    },
    ColorTrieNode {
        color: None,
        children: (685, 1),
    },
    ColorTrieNode {
        color: None,
        children: (684, 1),
    },
    ColorTrieNode {
        color: None,
        children: (683, 1),
    },
    ColorTrieNode {
        color: Some(105),
        children: (683, 0),
    },
    ColorTrieNode {
        color: None,
        children: (703, 1),
    },
    ColorTrieNode {
        color: None,
        children: (702, 1),
    },
    ColorTrieNode {
        color: None,
        children: (701, 1),
    },
    ColorTrieNode {
        color: None,
        children: (700, 1),
    },
    ColorTrieNode {
        color: None,
        children: (699, 1),
    },
    ColorTrieNode {
        color: None,
        children: (698, 1),
    },
    ColorTrieNode {
        color: None,
        children: (697, 1),
    },
    ColorTrieNode {
        color: None,
        children: (696, 1),
    },
    ColorTrieNode {
        color: Some(106),
        children: (696, 0),
    },
    ColorTrieNode {
        color: None,
        children: (714, 2),
    },
    ColorTrieNode {
        color: None,
        children: (712, 1),
    },
    ColorTrieNode {
        color: None,
        children: (711, 1),
    },
    ColorTrieNode {
        color: None,
        children: (710, 1),
    },
    ColorTrieNode {
        color: None,
        children: (709, 1),
    },
    ColorTrieNode {
        color: None,
        children: (708, 1),
    },
    ColorTrieNode {
        color: None,
        children: (707, 1),
    },
    ColorTrieNode {
        color: None,
        children: (706, 1),
    },
    ColorTrieNode {
        color: Some(107),
        children: (706, 0),
    },
    ColorTrieNode {
        color: None,
        children: (713, 1),
    },
    ColorTrieNode {
        color: Some(108),
        children: (713, 0),
    },
    ColorTrieNode {
        color: None,
        children: (717, 1),
    },
    ColorTrieNode {
        color: None,
        children: (716, 1),
    },
    ColorTrieNode {
        color: Some(109),
        children: (716, 0),
    },
    ColorTrieNode {
        color: None,
        children: (719, 1),
    },
    ColorTrieNode {
        color: None,
        children: (718, 1),
    },
    ColorTrieNode {
        color: Some(110),
        children: (718, 0),
    },
    ColorTrieNode {
        color: None,
        children: (728, 1),
    },
    ColorTrieNode {
        color: None,
        children: (727, 1),
    },
    ColorTrieNode {
        color: None,
        children: (726, 1),
    },
    ColorTrieNode {
        color: None,
        children: (725, 1),
    },
    ColorTrieNode {
        color: None,
        children: (724, 1),
    },
    ColorTrieNode {
        color: None,
        children: (723, 1),
    },
    ColorTrieNode {
        color: None,
        children: (722, 1),
    },
    ColorTrieNode {
        color: None,
        children: (721, 1),
    },
    ColorTrieNode {
        color: None,
        children: (720, 1),
    },
    ColorTrieNode {
        color: Some(111),
        children: (720, 0),
    },
    ColorTrieNode {
        color: None,
        children: (732, 1),
    },
    ColorTrieNode {
        color: None,
        children: (731, 1),
    },
    ColorTrieNode {
        color: None,
        children: (730, 1),
    },
    ColorTrieNode {
        color: None,
        children: (729, 1),
    },
    ColorTrieNode {
        color: Some(112),
        children: (729, 0),
    },
    ColorTrieNode {
        color: None,
        children: (756, 2),
    },
    ColorTrieNode {
        color: None,
        children: (739, 1),
    },
    ColorTrieNode {
        color: Some(113),
        children: (739, 0),
    },
    ColorTrieNode {
        color: None,
        children: (754, 2),
    },
    ColorTrieNode {
        color: None,
        children: (746, 1),
    },
    ColorTrieNode {
        color: None,
        children: (745, 1),
    },
    ColorTrieNode {
        color: None,
        children: (744, 1),
    },
    ColorTrieNode {
        color: None,
        children: (743, 1),
    },
    ColorTrieNode {
        color: None,
        children: (742, 1),
    },
    ColorTrieNode {
        color: None,
        children: (741, 1),
    },
    ColorTrieNode {
        color: None,
        children: (740, 1),
    },
    ColorTrieNode {
        color: Some(114),
        children: (740, 0),
    },
    ColorTrieNode {
        color: None,
        children: (753, 1),
    },
    ColorTrieNode {
        color: None,
        children: (752, 1),
    },
    ColorTrieNode {
        color: None,
        children: (751, 1),
    },
    ColorTrieNode {
        color: None,
        children: (750, 1),
    },
    ColorTrieNode {
        color: None,
        children: (749, 1),
    },
    ColorTrieNode {
        color: None,
        children: (748, 1),
    },
    ColorTrieNode {
        color: None,
        children: (747, 1),
    },
    ColorTrieNode {
        color: Some(115),
        children: (747, 0),
    },
    ColorTrieNode {
        color: None,
        children: (839, 8),
    },
    ColorTrieNode {
        color: None,
        children: (778, 3),
    },
    ColorTrieNode {
        color: None,
        children: (766, 1),
    },
    ColorTrieNode {
        color: None,
        children: (765, 1),
    },
    ColorTrieNode {
        color: None,
        children: (764, 1),
    },
    ColorTrieNode {
        color: None,
        children: (763, 1),
    },
    ColorTrieNode {
        color: None,
        children: (762, 1),
    },
    ColorTrieNode {
        color: None,
        children: (761, 1),
    },
    ColorTrieNode {
        color: None,
        children: (760, 1),
    },
    ColorTrieNode {
        color: None,
        children: (759, 1),
    },
    ColorTrieNode {
        color: None,
        children: (758, 1),
    },
    ColorTrieNode {
        color: Some(116),
        children: (758, 0),
    },
    ColorTrieNode {
        color: None,
        children: (769, 1),
    },
    ColorTrieNode {
        color: None,
        children: (768, 1),
    },
    ColorTrieNode {
        color: None,
        children: (767, 1),
    },
    ColorTrieNode {
        color: Some(117),
        children: (767, 0),
    },
    ColorTrieNode {
        color: None,
        children: (777, 1),
    },
    ColorTrieNode {
        color: None,
        children: (776, 1),
    },
    ColorTrieNode {
        color: None,
        children: (775, 1),
    },
    ColorTrieNode {
        color: None,
        children: (774, 1),
    },
    ColorTrieNode {
        color: None,
        children: (773, 1),
    },
    ColorTrieNode {
        color: None,
        children: (772, 1),
    },
    ColorTrieNode {
        color: None,
        children: (771, 1),
    },
    ColorTrieNode {
        color: None,
        children: (770, 1),
    },
    ColorTrieNode {
        color: Some(118),
        children: (770, 0),
    },
    ColorTrieNode {
        color: None,
        children: (792, 1),
    },
    ColorTrieNode {
        color: None,
        children: (791, 1),
    },
    ColorTrieNode {
        color: None,
        children: (789, 2),
    },
    ColorTrieNode {
        color: None,
        children: (784, 1),
    },
    ColorTrieNode {
        color: None,
        children: (783, 1),
    },
    ColorTrieNode {
        color: None,
        children: (782, 1),
    },
    ColorTrieNode {
        color: None,
        children: (781, 1),
    },
    ColorTrieNode {
        color: Some(119),
        children: (781, 0),
    },
    ColorTrieNode {
        color: None,
        children: (788, 1),
    },
    ColorTrieNode {
        color: None,
        children: (787, 1),
    },
    ColorTrieNode {
        color: None,
        children: (786, 1),
    },
    ColorTrieNode {
        color: None,
        children: (785, 1),
    },
    ColorTrieNode {
        color: Some(120),
        children: (785, 0),
    },
    ColorTrieNode {
        color: None,
        children: (799, 2),
    },
    ColorTrieNode {
        color: None,
        children: (795, 1),
    },
    ColorTrieNode {
        color: None,
        children: (794, 1),
    },
    ColorTrieNode {
        color: None,
        children: (793, 1),
    },
    ColorTrieNode {
        color: Some(121),
        children: (793, 0),
    },
    ColorTrieNode {
        color: None,
        children: (798, 1),
    },
    ColorTrieNode {
        color: None,
        children: (797, 1),
    },
    ColorTrieNode {
        color: None,
        children: (796, 1),
    },
    ColorTrieNode {
        color: Some(122),
        children: (796, 0),
    },
    ColorTrieNode {
        color: None,
        children: (806, 1),
    },
    ColorTrieNode {
        color: None,
        children: (805, 1),
    },
    ColorTrieNode {
        color: None,
        children: (804, 1),
    },
    ColorTrieNode {
        color: None,
        children: (803, 1),
    },
    ColorTrieNode {
        color: None,
        children: (802, 1),
    },
    ColorTrieNode {
        color: None,
        children: (801, 1),
    },
    ColorTrieNode {
        color: Some(123),
        children: (801, 0),
    },
    ColorTrieNode {
        color: None,
        children: (818, 1),
    },
    ColorTrieNode {
        color: None,
        children: (817, 1),
    },
    ColorTrieNode {
        color: None,
        children: (816, 1),
    },
    ColorTrieNode {
        color: None,
        children: (815, 1),
    },
    ColorTrieNode {
        color: None,
        children: (813, 2),
    },
    ColorTrieNode {
        color: None,
        children: (809, 1),
    },
    ColorTrieNode {
        color: None,
        children: (808, 1),
    },
    ColorTrieNode {
        color: None,
        children: (807, 1),
    },
    ColorTrieNode {
        color: Some(124),
        children: (807, 0),
    },
    ColorTrieNode {
        color: None,
        children: (812, 1),
    },
    ColorTrieNode {
        color: None,
        children: (811, 1),
    },
    ColorTrieNode {
        color: None,
        children: (810, 1),
    },
    ColorTrieNode {
        color: Some(125),
        children: (810, 0),
    },
    ColorTrieNode {
        color: None,
        children: (820, 1),
    },
    ColorTrieNode {
        color: None,
        children: (819, 1),
    },
    ColorTrieNode {
        color: Some(126),
        children: (819, 0),
    },
    ColorTrieNode {
        color: None,
        children: (830, 1),
    },
    ColorTrieNode {
        color: None,
        children: (829, 1),
    },
    ColorTrieNode {
        color: None,
        children: (828, 1),
    },
    ColorTrieNode {
        color: None,
        children: (827, 1),
    },
    ColorTrieNode {
        color: None,
        children: (826, 1),
    },
    ColorTrieNode {
        color: None,
        children: (825, 1),
    },
    ColorTrieNode {
        color: None,
        children: (824, 1),
    },
    ColorTrieNode {
        color: None,
        children: (823, 1),
    },
    ColorTrieNode {
        color: None,
        children: (822, 1),
    },
    ColorTrieNode {
        color: None,
        children: (821, 1),
    },
    ColorTrieNode {
        color: Some(127),
        children: (821, 0),
    },
    ColorTrieNode {
        color: None,
        children: (838, 1),
    },
    ColorTrieNode {
        color: None,
        children: (837, 1),
    },
    ColorTrieNode {
        color: None,
        children: (836, 1),
    },
    ColorTrieNode {
        color: None,
        children: (835, 1),
    },
    ColorTrieNode {
        color: None,
        children: (834, 1),
    },
    ColorTrieNode {
        color: None,
        children: (833, 1),
    },
    ColorTrieNode {
        color: None,
        children: (832, 1),
    },
    ColorTrieNode {
        color: None,
        children: (831, 1),
    },
    ColorTrieNode {
        color: Some(128),
        children: (831, 0),
    },
    ColorTrieNode {
        color: None,
        children: (866, 5),
    },
    ColorTrieNode {
        color: None,
        children: (847, 1),
    },
    ColorTrieNode {
        color: Some(129),
        children: (847, 0),
    },
    ColorTrieNode {
        color: None,
        children: (849, 1),
    },
    ColorTrieNode {
        color: None,
        children: (848, 1),
    },
    ColorTrieNode {
        color: Some(130),
        children: (848, 0),
    },
    ColorTrieNode {
        color: None,
        children: (854, 1),
    },
    ColorTrieNode {
        color: None,
        children: (853, 1),
    },
    ColorTrieNode {
        color: None,
        children: (852, 1),
    },
    ColorTrieNode {
        color: None,
        children: (851, 1),
    },
    ColorTrieNode {
        color: None,
        children: (850, 1),
    },
    ColorTrieNode {
        color: Some(131),
        children: (850, 0),
    },
    ColorTrieNode {
        color: None,
        children: (858, 1),
    },
    ColorTrieNode {
        color: None,
        children: (857, 1),
    },
    ColorTrieNode {
        color: None,
        children: (856, 1),
    },
    ColorTrieNode {
        color: None,
        children: (855, 1),
    },
    ColorTrieNode {
        color: Some(132),
        children: (855, 0),
    },
    ColorTrieNode {
        color: None,
        children: (865, 1),
    },
    ColorTrieNode {
        color: None,
        children: (864, 1),
    },
    ColorTrieNode {
        color: None,
        children: (863, 1),
    },
    ColorTrieNode {
        color: None,
        children: (862, 1),
    },
    ColorTrieNode {
        color: None,
        children: (861, 1),
    },
    ColorTrieNode {
        color: None,
        children: (860, 1),
    },
    ColorTrieNode {
        color: None,
        children: (859, 1),
    },
    ColorTrieNode {
        color: Some(133),
        children: (859, 0),
    },
    ColorTrieNode {
        color: None,
        children: (875, 1),
    },
    ColorTrieNode {
        color: None,
        children: (874, 1),
    },
    ColorTrieNode {
        color: None,
        children: (873, 1),
    },
    ColorTrieNode {
        color: None,
        children: (872, 1),
    },
    ColorTrieNode {
        color: None,
        children: (871, 1),
    },
    ColorTrieNode {
        color: Some(134),
        children: (871, 0),
    },
    ColorTrieNode {
        color: None,
        children: (888, 1),
    },
    ColorTrieNode {
        color: None,
        children: (886, 2),
    },
    ColorTrieNode {
        color: None,
        children: (877, 1),
    },
    ColorTrieNode {
        color: None,
        children: (876, 1),
    },
    ColorTrieNode {
        color: Some(135),
        children: (876, 0),
    },
    ColorTrieNode {
        color: None,
        children: (885, 1),
    },
    ColorTrieNode {
        color: None,
        children: (884, 1),
    },
    ColorTrieNode {
        color: Some(136),
        children: (883, 1),
    },
    ColorTrieNode {
        color: None,
        children: (882, 1),
    },
    ColorTrieNode {
        color: None,
        children: (881, 1),
    },
    ColorTrieNode {
        color: None,
        children: (880, 1),
    },
    ColorTrieNode {
        color: None,
        children: (879, 1),
    },
    ColorTrieNode {
        color: None,
        children: (878, 1),
    },
    ColorTrieNode {
        color: Some(137),
        children: (878, 0),
    },
    ColorTrieNode {
        color: None,
        children: (899, 1),
    },
    ColorTrieNode {
        color: None,
        children: (898, 1),
    },
    ColorTrieNode {
        color: None,
        children: (897, 1),
    },
    ColorTrieNode {
        color: None,
        children: (896, 1),
    },
    ColorTrieNode {
        color: None,
        children: (895, 1),
    },
    ColorTrieNode {
        color: Some(138),
        children: (894, 1),
    },
    ColorTrieNode {
        color: None,
        children: (893, 1),
    },
    ColorTrieNode {
        color: None,
        children: (892, 1),
    },
    ColorTrieNode {
        color: None,
        children: (891, 1),
    },
    ColorTrieNode {
        color: None,
        children: (890, 1),
    },
    ColorTrieNode {
        color: None,
        children: (889, 1),
    },
    ColorTrieNode {
        color: Some(139),
        children: (889, 0),
    },
];

pub static CHILDREN: &[(u8, u16)] = &[
    (5, 10),
    (21, 9),
    (12, 8),
    (2, 7),
    (0, 6),
    (5, 5),
    (3, 4),
    (9, 3),
    (5, 22),
    (20, 21),
    (9, 20),
    (8, 19),
    (23, 18),
    (0, 17),
    (5, 16),
    (21, 15),
    (17, 14),
    (9, 13),
    (20, 12),
    (5, 31),
    (14, 30),
    (9, 29),
    (18, 28),
    (1, 27),
    (13, 26),
    (1, 25),
    (21, 24),
    (5, 35),
    (18, 34),
    (21, 33),
    (12, 2),
    (14, 11),
    (17, 23),
    (26, 32),
    (5, 40),
    (7, 39),
    (9, 38),
    (5, 45),
    (21, 44),
    (17, 43),
    (19, 42),
    (11, 49),
    (4, 61),
    (14, 60),
    (15, 59),
    (13, 58),
    (12, 57),
    (1, 56),
    (0, 55),
    (4, 54),
    (5, 53),
    (8, 52),
    (3, 51),
    (3, 48),
    (14, 50),
    (20, 70),
    (5, 69),
    (12, 68),
    (15, 67),
    (9, 66),
    (22, 65),
    (0, 64),
    (5, 63),
    (1, 47),
    (21, 62),
    (14, 74),
    (23, 73),
    (15, 72),
    (4, 83),
    (15, 82),
    (15, 81),
    (23, 80),
    (0, 79),
    (25, 78),
    (12, 77),
    (18, 76),
    (5, 37),
    (9, 41),
    (12, 46),
    (18, 71),
    (21, 75),
    (5, 93),
    (21, 92),
    (12, 91),
    (2, 90),
    (0, 89),
    (20, 88),
    (5, 87),
    (4, 86),
    (5, 102),
    (19, 101),
    (21, 100),
    (5, 99),
    (18, 98),
    (20, 97),
    (18, 96),
    (5, 109),
    (20, 108),
    (1, 107),
    (12, 106),
    (15, 105),
    (3, 104),
    (1, 95),
    (15, 103),
    (12, 113),
    (5, 125),
    (21, 124),
    (12, 123),
    (2, 122),
    (0, 121),
    (18, 120),
    (5, 119),
    (23, 118),
    (15, 117),
    (12, 116),
    (11, 129),
    (12, 128),
    (9, 127),
    (6, 115),
    (19, 126),
    (1, 112),
    (14, 114),
    (18, 111),
    (14, 135),
    (15, 134),
    (19, 133),
    (13, 132),
    (9, 131),
    (14, 138),
    (1, 137),
    (1, 85),
    (8, 94),
    (15, 110),
    (18, 130),
    (25, 136),
    (5, 147),
    (21, 146),
    (12, 145),
    (14, 151),
    (1, 150),
    (25, 149),
    (4, 160),
    (15, 159),
    (18, 158),
    (14, 157),
    (5, 156),
    (4, 155),
    (12, 154),
    (25, 163),
    (14, 166),
    (5, 165),
    (1, 162),
    (5, 164),
    (15, 153),
    (18, 161),
    (9, 171),
    (11, 170),
    (1, 169),
    (8, 168),
    (1, 178),
    (20, 177),
    (14, 176),
    (5, 175),
    (7, 174),
    (1, 173),
    (14, 188),
    (5, 187),
    (5, 186),
    (18, 185),
    (7, 184),
    (5, 183),
    (22, 182),
    (9, 181),
    (5, 193),
    (7, 192),
    (14, 191),
    (4, 197),
    (9, 196),
    (8, 195),
    (1, 190),
    (3, 194),
    (12, 180),
    (18, 189),
    (4, 200),
    (5, 199),
    (14, 206),
    (15, 205),
    (13, 204),
    (12, 203),
    (14, 213),
    (5, 212),
    (5, 211),
    (18, 210),
    (7, 209),
    (1, 208),
    (5, 221),
    (21, 220),
    (12, 219),
    (25, 225),
    (1, 224),
    (18, 223),
    (2, 218),
    (7, 222),
    (5, 217),
    (20, 216),
    (1, 215),
    (1, 202),
    (5, 207),
    (12, 214),
    (5, 234),
    (19, 233),
    (9, 232),
    (15, 231),
    (21, 230),
    (17, 229),
    (18, 228),
    (21, 227),
    (20, 240),
    (5, 239),
    (12, 238),
    (15, 237),
    (9, 236),
    (2, 144),
    (3, 148),
    (7, 152),
    (11, 167),
    (13, 172),
    (15, 179),
    (18, 198),
    (19, 201),
    (20, 226),
    (22, 235),
    (0, 143),
    (11, 142),
    (18, 141),
    (11, 248),
    (14, 247),
    (9, 246),
    (5, 255),
    (21, 254),
    (12, 253),
    (2, 252),
    (25, 251),
    (11, 250),
    (16, 245),
    (19, 249),
    (0, 244),
    (16, 243),
    (5, 242),
    (25, 262),
    (1, 261),
    (18, 260),
    (7, 259),
    (0, 258),
    (13, 257),
    (5, 272),
    (21, 271),
    (12, 270),
    (2, 269),
    (0, 268),
    (18, 267),
    (5, 266),
    (7, 265),
    (4, 264),
    (1, 140),
    (5, 241),
    (9, 256),
    (15, 263),
    (11, 281),
    (3, 280),
    (9, 279),
    (18, 278),
    (2, 277),
    (5, 276),
    (18, 275),
    (5, 292),
    (20, 291),
    (9, 290),
    (8, 289),
    (23, 288),
    (0, 287),
    (12, 286),
    (1, 285),
    (18, 284),
    (15, 283),
    (14, 303),
    (5, 302),
    (5, 301),
    (18, 300),
    (7, 299),
    (0, 298),
    (20, 297),
    (19, 296),
    (5, 295),
    (18, 294),
    (1, 309),
    (9, 308),
    (19, 307),
    (8, 306),
    (3, 305),
    (9, 274),
    (12, 282),
    (15, 293),
    (21, 304),
    (15, 318),
    (18, 317),
    (15, 316),
    (2, 315),
    (19, 314),
    (14, 313),
    (9, 312),
    (5, 328),
    (20, 327),
    (9, 326),
    (8, 325),
    (23, 324),
    (0, 323),
    (20, 322),
    (19, 321),
    (15, 320),
    (4, 336),
    (15, 335),
    (18, 334),
    (14, 333),
    (5, 332),
    (4, 331),
    (12, 330),
    (25, 339),
    (23, 349),
    (15, 348),
    (12, 347),
    (12, 346),
    (5, 345),
    (25, 344),
    (0, 343),
    (14, 342),
    (5, 341),
    (1, 338),
    (5, 340),
    (1, 311),
    (8, 319),
    (15, 329),
    (18, 337),
    (23, 357),
    (5, 356),
    (4, 355),
    (25, 354),
    (5, 353),
    (11, 363),
    (14, 362),
    (9, 361),
    (16, 360),
    (0, 359),
    (14, 352),
    (20, 358),
    (15, 351),
    (4, 373),
    (5, 372),
    (18, 371),
    (0, 370),
    (14, 369),
    (15, 375),
    (1, 368),
    (7, 374),
    (9, 367),
    (4, 366),
    (25, 379),
    (18, 378),
    (15, 377),
    (14, 365),
    (22, 376),
    (9, 384),
    (11, 383),
    (1, 382),
    (8, 381),
    (8, 398),
    (19, 397),
    (21, 396),
    (12, 395),
    (2, 394),
    (0, 393),
    (18, 392),
    (5, 391),
    (4, 390),
    (14, 389),
    (5, 388),
    (14, 406),
    (5, 405),
    (5, 404),
    (18, 403),
    (7, 402),
    (0, 401),
    (14, 400),
    (22, 387),
    (23, 399),
    (14, 418),
    (15, 417),
    (6, 416),
    (6, 415),
    (9, 414),
    (8, 413),
    (3, 412),
    (0, 411),
    (14, 410),
    (15, 409),
    (13, 408),
    (5, 427),
    (21, 426),
    (12, 425),
    (12, 432),
    (1, 431),
    (18, 430),
    (14, 435),
    (1, 434),
    (15, 429),
    (25, 433),
    (23, 450),
    (15, 449),
    (12, 448),
    (12, 447),
    (5, 446),
    (25, 445),
    (4, 444),
    (15, 443),
    (18, 442),
    (14, 441),
    (5, 440),
    (4, 439),
    (12, 438),
    (25, 453),
    (14, 456),
    (5, 455),
    (1, 452),
    (5, 454),
    (15, 437),
    (18, 451),
    (11, 460),
    (14, 459),
    (9, 458),
    (14, 466),
    (15, 465),
    (13, 464),
    (12, 463),
    (14, 473),
    (5, 472),
    (5, 471),
    (18, 470),
    (7, 469),
    (1, 468),
    (5, 479),
    (21, 478),
    (12, 477),
    (2, 476),
    (25, 475),
    (25, 487),
    (1, 486),
    (18, 485),
    (7, 484),
    (5, 483),
    (20, 482),
    (1, 481),
    (5, 495),
    (21, 494),
    (12, 493),
    (2, 492),
    (12, 491),
    (5, 490),
    (5, 489),
    (1, 462),
    (5, 467),
    (11, 474),
    (12, 480),
    (20, 488),
    (23, 501),
    (15, 500),
    (12, 499),
    (12, 498),
    (5, 497),
    (2, 424),
    (3, 428),
    (7, 436),
    (16, 457),
    (19, 461),
    (25, 496),
    (0, 423),
    (20, 422),
    (8, 421),
    (14, 509),
    (5, 508),
    (5, 507),
    (18, 506),
    (7, 505),
    (0, 504),
    (5, 503),
    (14, 512),
    (5, 511),
    (7, 420),
    (13, 502),
    (14, 510),
    (1, 386),
    (5, 407),
    (9, 419),
    (1, 519),
    (20, 518),
    (14, 517),
    (5, 516),
    (14, 523),
    (15, 522),
    (15, 521),
    (7, 515),
    (18, 520),
    (5, 539),
    (14, 538),
    (9, 537),
    (18, 536),
    (1, 535),
    (13, 534),
    (1, 533),
    (21, 532),
    (17, 531),
    (5, 543),
    (21, 542),
    (12, 541),
    (4, 549),
    (9, 548),
    (8, 547),
    (3, 546),
    (18, 545),
    (5, 555),
    (12, 554),
    (16, 553),
    (18, 552),
    (21, 551),
    (14, 563),
    (5, 562),
    (5, 561),
    (18, 560),
    (7, 559),
    (1, 558),
    (5, 571),
    (21, 570),
    (12, 569),
    (2, 568),
    (5, 567),
    (20, 566),
    (1, 565),
    (14, 581),
    (5, 580),
    (5, 579),
    (18, 578),
    (7, 577),
    (7, 576),
    (14, 575),
    (9, 574),
    (18, 573),
    (5, 557),
    (12, 564),
    (16, 572),
    (5, 590),
    (19, 589),
    (9, 588),
    (15, 587),
    (21, 586),
    (17, 585),
    (18, 584),
    (21, 583),
    (4, 599),
    (5, 598),
    (18, 597),
    (20, 596),
    (5, 595),
    (12, 594),
    (15, 593),
    (9, 592),
    (1, 530),
    (2, 540),
    (15, 544),
    (16, 550),
    (19, 556),
    (20, 582),
    (22, 591),
    (0, 529),
    (13, 528),
    (21, 527),
    (9, 526),
    (4, 525),
    (5, 611),
    (21, 610),
    (12, 609),
    (2, 608),
    (0, 607),
    (20, 606),
    (8, 605),
    (7, 604),
    (9, 603),
    (14, 602),
    (13, 619),
    (1, 618),
    (5, 617),
    (18, 616),
    (3, 615),
    (0, 614),
    (20, 613),
    (5, 627),
    (19, 626),
    (15, 625),
    (18, 624),
    (0, 623),
    (25, 622),
    (20, 621),
    (4, 601),
    (14, 612),
    (19, 620),
    (14, 634),
    (9, 633),
    (19, 632),
    (1, 631),
    (3, 630),
    (3, 629),
    (1, 514),
    (5, 524),
    (9, 600),
    (15, 628),
    (5, 646),
    (20, 645),
    (9, 644),
    (8, 643),
    (23, 642),
    (0, 641),
    (15, 640),
    (10, 639),
    (1, 638),
    (25, 647),
    (22, 637),
    (1, 636),
    (5, 655),
    (3, 654),
    (1, 653),
    (12, 652),
    (0, 651),
    (2, 663),
    (1, 662),
    (18, 661),
    (4, 660),
    (0, 659),
    (5, 658),
    (22, 657),
    (4, 650),
    (9, 656),
    (4, 672),
    (5, 671),
    (18, 670),
    (0, 669),
    (5, 668),
    (7, 667),
    (14, 666),
    (4, 676),
    (9, 675),
    (8, 674),
    (1, 665),
    (3, 673),
    (12, 649),
    (18, 664),
    (4, 690),
    (15, 689),
    (18, 688),
    (14, 687),
    (5, 686),
    (4, 685),
    (12, 684),
    (14, 694),
    (5, 693),
    (5, 692),
    (15, 683),
    (18, 691),
    (5, 703),
    (19, 702),
    (9, 701),
    (15, 700),
    (21, 699),
    (17, 698),
    (18, 697),
    (21, 696),
    (4, 712),
    (5, 711),
    (18, 710),
    (20, 709),
    (5, 708),
    (12, 707),
    (15, 706),
    (9, 705),
    (7, 682),
    (20, 695),
    (22, 704),
    (0, 681),
    (5, 680),
    (16, 721),
    (9, 720),
    (8, 719),
    (23, 718),
    (0, 717),
    (1, 716),
    (25, 715),
    (1, 714),
    (12, 679),
    (16, 713),
    (6, 730),
    (6, 729),
    (21, 728),
    (16, 727),
    (0, 726),
    (8, 725),
    (3, 724),
    (21, 732),
    (1, 723),
    (18, 731),
    (11, 735),
    (14, 734),
    (13, 738),
    (21, 737),
    (5, 748),
    (21, 747),
    (12, 746),
    (2, 745),
    (0, 744),
    (18, 743),
    (5, 742),
    (4, 741),
    (23, 740),
    (5, 753),
    (12, 752),
    (16, 751),
    (18, 750),
    (1, 678),
    (5, 722),
    (9, 733),
    (12, 736),
    (15, 739),
    (21, 749),
    (4, 756),
    (14, 765),
    (23, 764),
    (15, 763),
    (18, 762),
    (2, 761),
    (0, 760),
    (25, 759),
    (5, 773),
    (21, 772),
    (12, 771),
    (2, 770),
    (0, 769),
    (12, 768),
    (1, 767),
    (19, 758),
    (25, 766),
    (5, 755),
    (15, 757),
    (14, 785),
    (23, 784),
    (15, 783),
    (18, 782),
    (2, 781),
    (0, 780),
    (5, 779),
    (12, 778),
    (4, 777),
    (14, 789),
    (15, 788),
    (13, 787),
    (14, 798),
    (23, 797),
    (15, 796),
    (18, 795),
    (2, 794),
    (0, 793),
    (25, 792),
    (4, 791),
    (4, 776),
    (12, 786),
    (14, 790),
    (14, 806),
    (5, 805),
    (5, 804),
    (18, 803),
    (12, 811),
    (12, 810),
    (5, 809),
    (8, 808),
    (7, 802),
    (19, 807),
    (0, 801),
    (1, 800),
    (1, 816),
    (14, 815),
    (14, 814),
    (18, 820),
    (5, 819),
    (22, 818),
    (5, 813),
    (12, 817),
    (5, 827),
    (21, 826),
    (12, 825),
    (2, 824),
    (0, 823),
    (25, 822),
    (5, 836),
    (21, 835),
    (12, 834),
    (25, 840),
    (1, 839),
    (18, 838),
    (2, 833),
    (7, 837),
    (0, 832),
    (5, 831),
    (20, 830),
    (1, 829),
    (23, 843),
    (15, 842),
    (14, 854),
    (5, 853),
    (5, 852),
    (18, 851),
    (7, 850),
    (0, 849),
    (7, 848),
    (14, 847),
    (9, 846),
    (18, 845),
    (5, 863),
    (21, 862),
    (12, 861),
    (2, 860),
    (0, 859),
    (12, 858),
    (5, 857),
    (5, 856),
    (1, 775),
    (5, 799),
    (9, 812),
    (11, 821),
    (12, 828),
    (14, 841),
    (16, 844),
    (20, 855),
    (14, 866),
    (12, 869),
    (1, 868),
    (5, 875),
    (12, 874),
    (20, 873),
    (19, 872),
    (9, 871),
    (15, 880),
    (20, 879),
    (1, 878),
    (13, 877),
    (5, 888),
    (19, 887),
    (9, 886),
    (15, 885),
    (21, 884),
    (17, 883),
    (18, 882),
    (1, 865),
    (5, 867),
    (8, 870),
    (15, 876),
    (21, 881),
    (20, 894),
    (5, 893),
    (12, 892),
    (15, 891),
    (9, 890),
    (20, 899),
    (1, 898),
    (5, 908),
    (11, 907),
    (15, 906),
    (13, 905),
    (19, 904),
    (0, 903),
    (5, 902),
    (20, 901),
    (5, 897),
    (9, 900),
    (8, 896),
    (14, 920),
    (5, 919),
    (5, 918),
    (18, 917),
    (7, 916),
    (0, 915),
    (23, 914),
    (15, 913),
    (12, 912),
    (12, 911),
    (5, 910),
    (1, 1),
    (2, 36),
    (3, 84),
    (4, 139),
    (6, 273),
    (7, 310),
    (8, 350),
    (9, 364),
    (11, 380),
    (12, 385),
    (13, 513),
    (14, 635),
    (15, 648),
    (16, 677),
    (18, 754),
    (19, 774),
    (20, 864),
    (22, 889),
    (23, 895),
    (25, 909),
];

pub static COLORS: &[Color] = &[
    Color::ALICE_BLUE,
    Color::ANTIQUE_WHITE,
    Color::AQUA,
    Color::AQUAMARINE,
    Color::AZURE,
    Color::BEIGE,
    Color::BISQUE,
    Color::BLACK,
    Color::BLANCHED_ALMOND,
    Color::BLUE,
    Color::BLUE_VIOLET,
    Color::BROWN,
    Color::BURLY_WOOD,
    Color::CADET_BLUE,
    Color::CHARTREUSE,
    Color::CHOCOLATE,
    Color::CORAL,
    Color::CORNFLOWER_BLUE,
    Color::CORNSILK,
    Color::CRIMSON,
    Color::CYAN,
    Color::DARK_BLUE,
    Color::DARK_CYAN,
    Color::DARK_GOLDENROD,
    Color::DARK_GRAY,
    Color::DARK_GREEN,
    Color::DARK_KHAKI,
    Color::DARK_MAGENTA,
    Color::DARK_OLIVEGREEN,
    Color::DARK_ORANGE,
    Color::DARK_ORCHID,
    Color::DARK_RED,
    Color::DARK_SALMON,
    Color::DARK_SEAGREEN,
    Color::DARK_SLATEBLUE,
    Color::DARK_SLATEGRAY,
    Color::DARK_TURQUOISE,
    Color::DARK_VIOLET,
    Color::DEEP_PINK,
    Color::DEEP_SKYBLUE,
    Color::DIM_GRAY,
    Color::DODGER_BLUE,
    Color::FIREBRICK,
    Color::FLORAL_WHITE,
    Color::FOREST_GREEN,
    Color::FUCHSIA,
    Color::GAINSBORO,
    Color::GHOST_WHITE,
    Color::GOLD,
    Color::GOLDENROD,
    Color::GRAY,
    Color::GREEN,
    Color::GREEN_YELLOW,
    Color::HONEYDEW,
    Color::HOT_PINK,
    Color::INDIAN_RED,
    Color::INDIGO,
    Color::IVORY,
    Color::KHAKI,
    Color::LAVENDER,
    Color::LAVENDER_BLUSH,
    Color::LAWN_GREEN,
    Color::LEMON_CHIFFON,
    Color::LIGHT_BLUE,
    Color::LIGHT_CORAL,
    Color::LIGHT_CYAN,
    Color::LIGHT_GOLDENRODYELLOW,
    Color::LIGHT_GREEN,
    Color::LIGHT_GRAY,
    Color::LIGHT_PINK,
    Color::LIGHT_SALMON,
    Color::LIGHT_SEAGREEN,
    Color::LIGHT_SKYBLUE,
    Color::LIGHT_SLATEGRAY,
    Color::LIGHT_STEELBLUE,
    Color::LIGHT_YELLOW,
    Color::LIME,
    Color::LIME_GREEN,
    Color::LINEN,
    Color::MAGENTA,
    Color::MAROON,
    Color::MEDIUM_AQUAMARINE,
    Color::MEDIUM_BLUE,
    Color::MEDIUM_ORCHID,
    Color::MEDIUM_PURPLE,
    Color::MEDIUM_SEAGREEN,
    Color::MEDIUM_SLATEBLUE,
    Color::MEDIUM_SPRINGGREEN,
    Color::MEDIUM_TURQUOISE,
    Color::MEDIUM_VIOLETRED,
    Color::MIDNIGHT_BLUE,
    Color::MINT_CREAM,
    Color::MISTY_ROSE,
    Color::MOCCASIN,
    Color::NAVAJO_WHITE,
    Color::NAVY,
    Color::OLD_LACE,
    Color::OLIVE,
    Color::OLIVE_DRAB,
    Color::ORANGE,
    Color::ORANGE_RED,
    Color::ORCHID,
    Color::PALE_GOLDENROD,
    Color::PALE_GREEN,
    Color::PALE_TURQUOISE,
    Color::PALE_VIOLETRED,
    Color::PAPAYA_WHIP,
    Color::PEACH_PUFF,
    Color::PERU,
    Color::PINK,
    Color::PLUM,
    Color::POWDER_BLUE,
    Color::PURPLE,
    Color::RED,
    Color::ROSY_BROWN,
    Color::ROYAL_BLUE,
    Color::SADDLE_BROWN,
    Color::SALMON,
    Color::SANDY_BROWN,
    Color::SEA_GREEN,
    Color::SEA_SHELL,
    Color::SIENNA,
    Color::SILVER,
    Color::SKY_BLUE,
    Color::SLATE_BLUE,
    Color::SLATE_GRAY,
    Color::SNOW,
    Color::SPRING_GREEN,
    Color::STEEL_BLUE,
    Color::TAN,
    Color::TEAL,
    Color::THISTLE,
    Color::TOMATO,
    Color::TURQUOISE,
    Color::VIOLET,
    Color::WHEAT,
    Color::WHITE,
    Color::WHITE_SMOKE,
    Color::YELLOW,
    Color::YELLOW_GREEN,
];
